### ISSUE TITLE
Definition of client.rack at CommonConfig level causes kafka ProducerConfig to complain

### ISSUE THREAD

**Issue by kromanovs** [evolution-gaming/skafka#260]
Since introduction of `com.evolutiongaming.skafka.CommonConfig.clientRack` property that is supplied to both Consumer and Producer config of Kafka client, there are following warnings printed to application log if there's a producer used:
```
[org.apache.kafka.clients.producer.ProducerConfig] - The configuration 'client.rack' was supplied but isn't a known config.
```

As per [documentation](https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html) the `client.rack` property is applicable to Consumer only.

**Comment by t3hnar** [comment]
fixed in 13.0.0 & 11.11.0,
but note that those are not binary backward compatible changes
