### ISSUE TITLE
Circular dependency between skafka and smetrics

### ISSUE THREAD

**Issue by Z1kkurat** [evolution-gaming/skafka#338]
There's a circular dependency between [skafka](https://github.com/evolution-gaming/skafka/blob/195cbf5ec276fae72a20fe0f1623597f1d97d7e8/project/Dependencies.scala#L14) and [smetrics](https://github.com/evolution-gaming/smetrics/blob/270cd96f90421b87eff62137ebd8f6a6859801bd/project/Dependencies.scala#L12). It's caused by usages of `com.evolutiongaming.smetrics.MeasureDuration` in `Consumer`, `ConsumerLogging`, `ConsumerMetrics`, `ConsumerOf`, `RebalanceListener` and the corresponding Producer-related classes (also `com.evolutiongaming.smetrics.{CollectorRegistry, LabelNames, Quantiles}` in `ConsumerMetrics` and `ProducerMetrics`).

There can be multiple ways to mitigate that:
1. Move metrics-related code from `skafka` to `smetrics`. This means introducing a version of `MeasureDuration` local to `skafka` codebase and moving specific implementations of `ConsumerMetrics` and `ProducerMetrics` (using `CollectorRegistry`) to `smetrics`. This might be reasonable in the sense that a user can first depend on `skafka` (a Kafka client with no additional features) and later bring in a dependency to `smetrics` that contains additional metrics-related functionality, not directly related to the interaction with Kafka
2. Move metrics-related code from `smetrics` to `skafka`. This means removing `kafka` submodule from `smetrics` and moving `KafkaMetricsCollector` to `skafka` (it's the single class in the module). It would somewhat contradict the concept of `smetrics` being an additional library, providing features on top of other libraries via plug-in modules (`doobie`, `http4s`, etc.); also, it would impose a dependency on `smetrics` in `skafka` which is already there at the moment.

**Comment by t3hnar** [comment]
let's move `MeasureDuration` to `cats-helper`

**Comment by Z1kkurat** [comment]
> let's move MeasureDuration to cats-helper

That's a good call. However, it won't solve the issue as there'll still be usage of `com.evolutiongaming.smetrics.{CollectorRegistry, LabelNames, Quantiles}` in `ProducerMetrics` and `ConsumerMetrics`. And, in turn, those are part of method signatures in `ConsumerOf`/`Consumer`/`ProducerOf`/`Producer`: [ConsumerOps.withMetrics1](https://github.com/evolution-gaming/skafka/blob/195cbf5ec276fae72a20fe0f1623597f1d97d7e8/skafka/src/main/scala/com/evolutiongaming/skafka/consumer/Consumer.scala#L953), [ConsumerOf.apply](https://github.com/evolution-gaming/skafka/blob/195cbf5ec276fae72a20fe0f1623597f1d97d7e8/skafka/src/main/scala/com/evolutiongaming/skafka/consumer/ConsumerOf.scala#L26), [Producer.apply](https://github.com/evolution-gaming/skafka/blob/195cbf5ec276fae72a20fe0f1623597f1d97d7e8/skafka/src/main/scala/com/evolutiongaming/skafka/producer/Producer.scala#L229), [ProducerOps.withMetrics](https://github.com/evolution-gaming/skafka/blob/195cbf5ec276fae72a20fe0f1623597f1d97d7e8/skafka/src/main/scala/com/evolutiongaming/skafka/producer/Producer.scala#L348), [ProducerOf.apply](https://github.com/evolution-gaming/skafka/blob/195cbf5ec276fae72a20fe0f1623597f1d97d7e8/skafka/src/main/scala/com/evolutiongaming/skafka/producer/ProducerOf.scala#L23).

**Comment by t3hnar** [comment]
for those parts I'd suggest to move `KafkaMetricsCollector` module to `skafka` project

**Comment by Z1kkurat** [comment]
I'll implement this in multiple steps:
- [x] Move `MeasureDuration` to cats-helper:  done in https://github.com/evolution-gaming/cats-helper/pull/213 and https://github.com/evolution-gaming/cats-helper/pull/214
- [ ] Introduce `KafkaMetricsCollector` to `skafka`; release a new minor version
- [ ] Update `smetrics`
  - bump `cats-helper` version
  - use the new `MeasureDuration` from `cats-helper`
  - drop `KafkaMetricsCollector`
  - remove `skafka` dependency
  - release a new major version

**Comment by Z1kkurat** [comment]
Resolved, corresponding releases:
smetrics:
- https://github.com/evolution-gaming/smetrics/releases/tag/v2.0.0
- https://github.com/evolution-gaming/smetrics/releases/tag/v0.5.0

skafka:
- https://github.com/evolution-gaming/skafka/releases/tag/v15.1.0
- https://github.com/evolution-gaming/skafka/releases/tag/v11.15.0

cats-helper:
- https://github.com/evolution-gaming/cats-helper/releases/tag/v3.5.0
- https://github.com/evolution-gaming/cats-helper/releases/tag/v2.11.0
